In [4]:
import numpy as np


def create_segments(matrix, num_splits):
    matrix_rows, matrix_cols = matrix.shape
    split_size = matrix_rows // num_splits
    
    segments = []
    
    for i in range(num_splits):
        for j in range(num_splits):
            segment = matrix[i * split_size: (i + 1) * split_size, j * split_size: (j + 1) * split_size]
            segments.append(segment)
    
    return segments

matrix_size = 6
last_value = matrix_size * matrix_size

matrix = np.arange(1, last_value + 1).reshape(matrix_size, matrix_size)

num_splits = 3
segments = create_segments(matrix, num_splits)

print(matrix)

for i, segment in enumerate(segments):
    print(f"Segment {i+1}:")
    print(segment)



[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Segment 1:
[[1 2]
 [7 8]]
Segment 2:
[[ 3  4]
 [ 9 10]]
Segment 3:
[[ 5  6]
 [11 12]]
Segment 4:
[[13 14]
 [19 20]]
Segment 5:
[[15 16]
 [21 22]]
Segment 6:
[[17 18]
 [23 24]]
Segment 7:
[[25 26]
 [31 32]]
Segment 8:
[[27 28]
 [33 34]]
Segment 9:
[[29 30]
 [35 36]]
